CREATE TABLE posts (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL,
  url VARCHAR(300) NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  score INT DEFAULT 0 NOT NULL,
  owner VARCHAR(300) DEFAULT NULL,
  vote INT DEFAULT 0 NOT NULL
);